import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { envDir } from '../paths.js';
import { generatedHeader, makeGeneratedAdapter, parseArrayConst } from './generated-file.js';

export const id = 'pi';
export const name = 'Pi';

/**
 * Pi has no hook entries in a settings file. Instead it loads extensions —
 * TypeScript modules that subscribe to events programmatically:
 *
 *   export default function (pi) { pi.on("session_start", async () => {}) }
 *
 * so this adapter generates a whole extension file rather than editing a
 * config. The file-ownership rules that follow from that are shared with the
 * other generated-file agent (see generated-file.js); what lives here is the
 * template, the events and where Pi looks for them.
 *
 * Extensions run on Node (loaded through jiti), so the generated file can spawn
 * the same hook shim the other agents use — which keeps binding, volume and
 * playback resolution in exactly one place.
 */

export const EXTENSION_FILENAME = 'agentfx.ts';

/**
 * Pi's own override: "Override the config directory; default is ~/.pi/agent".
 * Note it points at the agent directory, not at ~/.pi.
 */
export const configDir = envDir('PI_CODING_AGENT_DIR', () =>
  path.join(os.homedir(), '.pi', 'agent')
);

export function defaultSettingsPath() {
  return path.join(configDir(), 'extensions', EXTENSION_FILENAME);
}

export function detect() {
  return fs.existsSync(configDir());
}

/**
 * Only events that observe. Pi handlers can change behaviour through their
 * return value — `tool_call` can block a tool, `input` can rewrite a prompt,
 * `context` can rewrite messages — and a sound effect has no business being
 * anywhere near that, so those events are deliberately not offered.
 */
export const events = [
  {
    id: 'agent_settled',
    label: 'Agent finished',
    description: 'Pi has no automatic continuation left — the closest thing to "done".',
    matcher: false
  },
  {
    id: 'agent_end',
    label: 'Response finished',
    description: 'An LLM run ended. Fires again if Pi retries or auto-compacts.',
    matcher: false
  },
  {
    id: 'turn_start',
    label: 'Turn started',
    description: 'A response-and-tools cycle began.',
    matcher: false
  },
  {
    id: 'turn_end',
    label: 'Turn finished',
    description: 'A response-and-tools cycle completed.',
    matcher: false
  },
  {
    id: 'tool_execution_start',
    label: 'Before tool use',
    description: 'A tool is about to run. Pi has no matcher, so this fires for every tool.',
    matcher: false,
    throttle: 2
  },
  {
    id: 'tool_execution_end',
    label: 'After tool use',
    description: 'A tool finished running.',
    matcher: false,
    throttle: 2
  },
  {
    id: 'session_start',
    label: 'Session started',
    description: 'A session began — on startup, reload, resume or fork.',
    matcher: false
  },
  {
    id: 'session_shutdown',
    label: 'Session ended',
    description: 'The session is being torn down.',
    matcher: false
  },
  {
    id: 'session_compact',
    label: 'After compact',
    description: 'Compaction finished.',
    matcher: false
  }
];

/** Pi discovers extensions per user and per project. */
export const SCOPES = {
  user: {
    label: 'Global',
    hint: 'Every project, just for you',
    needsDirectory: false,
    default: true
  },
  project: {
    label: 'This project',
    hint: 'One project — Pi loads it once you trust the project',
    needsDirectory: true,
    warn: 'This file lives in the repo.',
    file: path.join('.pi', 'extensions', EXTENSION_FILENAME)
  },
  custom: {
    label: 'Custom path',
    hint: 'Point at any extension file',
    needsDirectory: false
  }
};

/* ---------------- the generated extension ---------------- */

/** Marks the file as ours, so we never overwrite one somebody else wrote. */
export const MARKER = 'Generated by agentfx';

/** Reads back the events a generated extension subscribes to. */
export function parseEvents(source) {
  return parseArrayConst(source, 'AGENTFX_EVENTS');
}

/** Reads back the argv a generated extension will spawn. Null if unreadable. */
export function parseCommand(source) {
  const argv = parseArrayConst(source, 'AGENTFX_COMMAND');
  return argv.length ? argv : null;
}

export function buildExtension(eventIdList, argv) {
  const header = generatedHeader({
    marker: MARKER,
    summary: '// Plays a sound effect when Pi emits one of the events bound in the agentfx UI.',
    agentId: id,
    constants: [
      `const AGENTFX_EVENTS = ${JSON.stringify(eventIdList)};`,
      `const AGENTFX_COMMAND = ${JSON.stringify(argv)};`
    ].join('\n')
  });

  return `${header}
export default function (pi) {
  for (const event of AGENTFX_EVENTS) {
    // Returns nothing: these are observation-only events, and a handler that
    // returned a value could change how Pi behaves.
    pi.on(event, async () => {
      play(event);
    });
  }
}
`;
}

/** How generated-file.js recognises and reads back the files this agent owns. */
const SPEC = {
  marker: MARKER,
  noun: 'extension',
  build: buildExtension,
  parseEvents,
  parseCommand
};

export const { eventIds, resolveTargetPath, listTargets, sync, status, inspect } =
  makeGeneratedAdapter({ id, events, scopes: SCOPES, defaultSettingsPath, detect, spec: SPEC });
