import fs from 'node:fs';
import path from 'node:path';
import { agentfxHome, packageRoot } from './paths.js';
import { ensureHomeFile } from './home-file.js';

/**
 * A launcher that lives in the user's own directory rather than in the
 * installed package, so `npm uninstall -g agentfx` cannot delete it.
 *
 * Hooks point at this file instead of at the `agentfx` command. When the
 * package is still installed it plays the sound; when the package has been
 * removed it exits 0 without a word, so leftover hooks cannot spam an agent
 * with "command not found" on every event.
 *
 * The trade-off, deliberately chosen: a forgotten `agentfx uninstall` now fails
 * silently rather than loudly. `agentfx uninstall` remains the thing that
 * actually removes the hooks; this only stops the leftovers from being noisy.
 */

/**
 * The filename carries the product name because it is how agentfx recognises
 * its own hooks. It used to be `hook.mjs`, identified by the `.agentfx`
 * directory around it — which silently stopped working whenever AGENTFX_HOME
 * pointed somewhere else, leaving hooks that `sync` duplicated instead of
 * replacing and that `uninstall` could not find.
 */
export function hookShimPath() {
  return path.join(agentfxHome(), 'agentfx-hook.js');
}

/** Shims from earlier versions, removed once their replacement is in place. */
function legacyShimPaths() {
  return [path.join(agentfxHome(), 'agentfx-hook.mjs'), path.join(agentfxHome(), 'hook.mjs')];
}

/** The module the shim delegates to, recorded as an absolute path. */
function playModulePath() {
  return path.join(packageRoot, 'src', 'play.js');
}

/**
 * The shim is written as CommonJS, which is what makes the `.js` name safe: it
 * sits in a directory with no package.json, so Node parses `.js` there as
 * CommonJS regardless of what this package declares. ESM syntax — `import`, or
 * the top-level `await` this used to rely on — is a syntax error in that
 * position and would fail on every hook fire.
 *
 * `play.js` is still ESM, so it is reached through dynamic `import()`, which is
 * available from CommonJS. The result is deliberately not awaited at the top
 * level; `.then` keeps the file parseable under both module systems.
 */
export function buildHookShim(playModule = playModulePath()) {
  return `// Generated by agentfx — do not edit; it is rewritten on every sync.
//
// Hooks call this file rather than the \`agentfx\` command so that uninstalling
// the package leaves a harmless no-op behind instead of a broken command.
// If the package is gone, exit 0 silently and let the agent carry on.
//
// CommonJS on purpose: this file has no package.json above it, so Node reads a
// .js here as CommonJS and ESM syntax would not parse.
const fs = require('node:fs');
const { pathToFileURL } = require('node:url');

const playModule = ${JSON.stringify(playModule)};
if (!fs.existsSync(playModule)) process.exit(0);

// Hooks read "<prefix> play <agent> <event>" whichever prefix is in use, so the
// leading verb is accepted here to keep every installed command the same shape.
const args = process.argv.slice(2);
if (args[0] === 'play') args.shift();

import(pathToFileURL(playModule).href).then(({ playEvent }) => {
  playEvent({ agentId: args[0], event: args[1] });
});
`;
}

/**
 * Writes the shim if missing or stale. Returns null when it cannot be created,
 * which tells the caller to fall back to invoking agentfx directly.
 */
export function ensureHookShim() {
  const file = ensureHomeFile(hookShimPath(), buildHookShim());
  // Only once the replacement is actually in place — a failed write must not
  // leave the user with neither shim.
  if (file) removeLegacyShim();
  return file;
}

/**
 * Deletes shims from earlier versions once their replacement exists. Only ever
 * removes a file agentfx generated: `hook.mjs` in particular is generic enough
 * that someone else's could be sitting there.
 */
function removeLegacyShim() {
  for (const legacy of legacyShimPaths()) {
    try {
      if (fs.readFileSync(legacy, 'utf8').includes('Generated by agentfx')) {
        fs.rmSync(legacy, { force: true });
      }
    } catch {
      // Absent, unreadable, or not ours — leave it alone.
    }
  }
}
