import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import { execFileSync } from 'node:child_process';
import { sandbox, binPath, boundConfig } from '../helpers/sandbox.js';
import { startServer } from '../../src/server.js';
import * as opencode from '../../src/agents/opencode.js';

const cli = (args, box) =>
  execFileSync(process.execPath, [binPath, ...args], { encoding: 'utf8', env: box.env });

async function serve(t, label) {
  const box = sandbox(label);
  const { server, url } = await startServer({ port: 0 });
  t.after(async () => {
    server.closeAllConnections();
    await new Promise((resolve) => server.close(resolve));
    box.cleanup();
  });

  const put = (agent, event, body) =>
    fetch(`${url}/api/bindings/${agent}/${event}`, {
      method: 'PUT',
      headers: { 'content-type': 'application/json' },
      body: JSON.stringify(body)
    });

  const state = async () => (await fetch(`${url}/api/state`)).json();
  return { box, put, state };
}

test('state exposes opencode with its own events and its own file', async (t) => {
  const { box, state } = await serve(t, 'opencode-state');
  const payload = await state();

  const agent = payload.agents.find((a) => a.id === 'opencode');
  assert.equal(agent.name, 'opencode');
  assert.ok(agent.events.some((e) => e.id === 'session.idle'));
  assert.ok(agent.events.some((e) => e.id === 'tool.execute.after'));
  assert.equal(agent.targets[0].path, box.opencodePluginFile, 'sandboxed, not the real config dir');
});

test('binding an opencode event writes the plugin', async (t) => {
  const { box, put, state } = await serve(t, 'opencode-bind');

  const response = await put('opencode', 'session.idle', { soundId: 'bundled:task-complete' });
  assert.equal(response.status, 200);

  const source = box.readOpencodePlugin();
  assert.match(source, /Generated by agentfx/);
  assert.match(source, /"play", "opencode", event/, 'resolved against opencode bindings');

  const agent = (await state()).agents.find((a) => a.id === 'opencode');
  assert.deepEqual(agent.targets[0].installed, ['session.idle']);
});

test('a chatty opencode event gets its suggested rate limit on first bind', async (t) => {
  const { put, state } = await serve(t, 'opencode-throttle');

  await put('opencode', 'tool.execute.after', { soundId: 'bundled:blip' });
  const bindings = (await state()).bindings.opencode;
  const gap = bindings['tool.execute.after'].minInterval;
  assert.equal(gap, 2, 'every tool call would otherwise sound');
});

test('unknown opencode events are rejected', async (t) => {
  const { put } = await serve(t, 'opencode-bad-event');
  assert.equal((await put('opencode', 'session.nope', { soundId: 'bundled:blip' })).status, 404);
  // Claude has this event, opencode does not — the check must be per agent.
  assert.equal((await put('opencode', 'Stop', { soundId: 'bundled:blip' })).status, 404);
});

test('sync, status and uninstall cover opencode alongside the others', (t) => {
  const box = sandbox('opencode-cli');
  t.after(() => box.cleanup());
  box.writeSettings({});
  box.writeConfig({
    ...boundConfig({}),
    bindings: {
      claude: { Stop: { soundId: 'bundled:blip', volume: 100, enabled: true, matcher: '' } },
      opencode: {
        'session.idle': { soundId: 'bundled:chime', volume: 100, enabled: true, matcher: '' }
      }
    }
  });

  const synced = cli(['sync'], box);
  assert.match(synced, /opencode/);
  assert.ok(box.opencodePluginExists(), 'opencode plugin written');
  assert.deepEqual(opencode.parseEvents(box.readOpencodePlugin()), ['session.idle']);

  const status = cli(['status'], box);
  assert.match(status, /session\.idle/);

  const removed = cli(['uninstall'], box);
  assert.match(removed, /fully unhooked/);
  assert.equal(box.opencodePluginExists(), false, 'opencode cleaned up too');
  assert.ok(!box.readSettings().hooks, 'and claude with it');
});

test('--agent narrows sync to opencode', (t) => {
  const box = sandbox('opencode-narrow');
  t.after(() => box.cleanup());
  box.writeConfig({
    ...boundConfig({}),
    bindings: {
      claude: { Stop: { soundId: 'bundled:blip', volume: 100, enabled: true, matcher: '' } },
      opencode: {
        'session.idle': { soundId: 'bundled:chime', volume: 100, enabled: true, matcher: '' }
      }
    }
  });

  cli(['sync', '--agent', 'opencode'], box);
  assert.ok(box.opencodePluginExists(), 'opencode written');
  assert.equal(box.settingsExists(), false, 'claude left alone');
});

test('the command the plugin spawns is runnable, and silent', (t) => {
  const box = sandbox('opencode-exec');
  t.after(() => box.cleanup());
  box.writeConfig({
    ...boundConfig({}),
    masterVolume: 0,
    bindings: {
      opencode: {
        'session.idle': { soundId: 'bundled:blip', volume: 100, enabled: true, matcher: '' }
      }
    }
  });

  cli(['sync', '--agent', 'opencode'], box);

  // Spawned as argv, exactly as the generated plugin spawns it — no shell.
  const argv = opencode.parseCommand(box.readOpencodePlugin());
  const output = execFileSync(argv[0], [...argv.slice(1), 'play', 'opencode', 'session.idle'], {
    encoding: 'utf8',
    env: box.env
  });

  assert.equal(output, '', 'silent on the agent hot path');
  assert.equal(fs.existsSync(box.logFile), false, 'no errors logged');
});

test('doctor reports opencode without inventing a problem', (t) => {
  const box = sandbox('opencode-doctor');
  t.after(() => box.cleanup());
  box.writeConfig({
    // A real volume, so the only failure doctor could report is one about the
    // plugin. `--silent` is what keeps the suite quiet here, not a zero gain.
    ...boundConfig({}, { masterVolume: 70 }),
    bindings: {
      opencode: {
        'session.idle': { soundId: 'bundled:blip', volume: 100, enabled: true, matcher: '' }
      }
    }
  });
  cli(['sync', '--agent', 'opencode'], box);

  // Exits 0, or execFileSync throws — a freshly synced plugin is not a problem.
  const report = cli(['doctor', '--agent', 'opencode', '--silent'], box);
  assert.match(report, /opencode/);
  assert.match(report, /1 hook\(s\): session\.idle/, 'the plugin is seen as installed');
  assert.doesNotMatch(report, /point at a different command/, 'a fresh sync has not drifted');
  assert.match(report, /No problems found/);
});
